
package com.kitabxana.frame;

import javax.swing.table.DefaultTableModel;
import com.kitabxana.model.AddKitabxana;
import com.kitabxana.model.BookSort;
import com.kitabxana.dboperation.DBOperation;
import com.kitabxana.model.LoginStudent;

/**
 *
 * @author Ramin
 */
public class AddBookKitabxana extends javax.swing.JFrame {

    /**
     * Creates new form AddBookKitabxana
     */
    DBOperation db = new DBOperation();

    public AddBookKitabxana() {
        initComponents();
        for (BookSort sort : db.allBookSort()) {
            cmbBookSort.addItem(sort);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        tfBookId = new javax.swing.JTextField();
        tfRefNumber = new javax.swing.JTextField();
        cmbBookSort = new javax.swing.JComboBox();
        lblName1 = new javax.swing.JLabel();
        lblBookAbout = new javax.swing.JLabel();
        tfSutunNumber = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        tfBookName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        tfYaziciName = new javax.swing.JTextField();
        tfSiraNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBook = new javax.swing.JTable();
        btnUpdateBook = new javax.swing.JButton();
        lblMainMenu = new javax.swing.JLabel();
        btnAddBook = new javax.swing.JButton();
        btnDeleteBook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taBookAbout = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ID :");

        tfRefNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        cmbBookSort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblName1.setText("Kitabın növü :");

        lblBookAbout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBookAbout.setText("Kitab haqqında :");

        tfSutunNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAge.setText("Rəf nömrəsi :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Sıra nömrəsi :");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblName.setText("Kitab adı :");

        tfBookName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Sütun nömrəsi :");

        lblSurname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSurname.setText("Yazıçının adı :");

        tfYaziciName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        tfSiraNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Azərbaycan Dövlət Neft Akademiyası");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kitabxanaya kitab əlavə edin");

        tbBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kitabın adı", "Yazıçının adı", "Kitabın növü", "Rəf nömrəsi", "Sıra nömrəsi", "Sütun nömrəsi"
            }
        ));
        tbBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBook);

        btnUpdateBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdateBook.setText("Kitab dəyişdirmək");
        btnUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookActionPerformed(evt);
            }
        });

        lblMainMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMainMenu.setText("Ana səhifə");
        lblMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainMenuMouseClicked(evt);
            }
        });

        btnAddBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddBook.setText("Kitab əlavə et");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnDeleteBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeleteBook.setText("Silmək");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });

        taBookAbout.setColumns(20);
        taBookAbout.setLineWrap(true);
        taBookAbout.setRows(5);
        taBookAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        taBookAbout.setHighlighter(null);
        jScrollPane2.setViewportView(taBookAbout);
        taBookAbout.getAccessibleContext().setAccessibleParent(lblBookAbout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblSurname)
                    .addComponent(lblAge)
                    .addComponent(jLabel4)
                    .addComponent(lblName1)
                    .addComponent(jLabel5)
                    .addComponent(lblBookAbout)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddBook)
                        .addGap(91, 91, 91)
                        .addComponent(btnUpdateBook)
                        .addGap(81, 81, 81)
                        .addComponent(btnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(lblMainMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSutunNumber)
                            .addComponent(tfSiraNumber)
                            .addComponent(tfBookName)
                            .addComponent(tfYaziciName)
                            .addComponent(tfRefNumber)
                            .addComponent(tfBookId)
                            .addComponent(cmbBookSort, 0, 197, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(74, 74, 74))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSurname)
                            .addComponent(tfYaziciName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBookSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(tfRefNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfSiraNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfSutunNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lblBookAbout))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateBook)
                    .addComponent(btnAddBook)
                    .addComponent(btnDeleteBook)
                    .addComponent(lblMainMenu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBookMouseClicked
        int rowNum = tbBook.getSelectedRow();
        tfBookId.setText(tbBook.getValueAt(rowNum, 0).toString());
        tfBookName.setText(tbBook.getValueAt(rowNum, 1).toString());
        tfYaziciName.setText(tbBook.getValueAt(rowNum, 2).toString());

        tfRefNumber.setText(tbBook.getValueAt(rowNum, 5).toString());
        tfSiraNumber.setText(tbBook.getValueAt(rowNum, 6).toString());
        tfSutunNumber.setText(tbBook.getValueAt(rowNum, 7).toString());
        taBookAbout.setText(tbBook.getValueAt(rowNum, 8).toString());
    }//GEN-LAST:event_tbBookMouseClicked

    private void btnUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookActionPerformed
        AddKitabxana ak = new AddKitabxana();

        ak.setId(Integer.parseInt(tfBookId.getText()));
        ak.setBookName(tfBookName.getText());
        ak.setYaziciName(tfYaziciName.getText());

        ak.setBookSort(cmbBookSort.getSelectedItem().toString());
        ak.setRefNumber(tfRefNumber.getText());
        ak.setSiraNumber(tfSiraNumber.getText());
        ak.setSutunNumber(tfSutunNumber.getText());
        ak.setBookAbout(taBookAbout.getText());
        db.updateBooksByID(ak);

        DefaultTableModel tableModel = (DefaultTableModel) tbBook.getModel();
        tableModel.setRowCount(0);
        formWindowOpened(null);

        tfBookName.setText("");
        tfYaziciName.setText("");

        tfRefNumber.setText("");
        tfSiraNumber.setText("");
        tfSutunNumber.setText("");
        tfBookId.setText("");
        taBookAbout.setText("");
    }//GEN-LAST:event_btnUpdateBookActionPerformed

    private void lblMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainMenuMouseClicked
        new StartPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMainMenuMouseClicked

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed

        AddKitabxana ak = new AddKitabxana();
        BookSort bs = new BookSort();
        LoginStudent ls = new LoginStudent();

        ak.setBookName(tfBookName.getText());
        ak.setYaziciName(tfYaziciName.getText());
        ak.setBookSort(cmbBookSort.getSelectedItem().toString());
        ak.setRefNumber(tfRefNumber.getText());
        ak.setSiraNumber(tfSiraNumber.getText());
        ak.setSutunNumber(tfSutunNumber.getText());
        ak.setBookAbout(taBookAbout.getText());

        db.insertBook(ak);

        DefaultTableModel tableModel = (DefaultTableModel) tbBook.getModel();
        tableModel.setRowCount(0);
        formWindowOpened(null);

        tfBookName.setText("");
        tfYaziciName.setText("");

        tfRefNumber.setText("");
        tfSiraNumber.setText("");
        tfSutunNumber.setText("");
        tfBookId.setText("");
        taBookAbout.setText("");

    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        AddKitabxana ak = new AddKitabxana();
        ak.setId(Integer.parseInt(tfBookId.getText()));
        db.deleteBookByID(ak);

        DefaultTableModel tableModel = (DefaultTableModel) tbBook.getModel();
        tableModel.setRowCount(0);
        formWindowOpened(null);

        tfBookName.setText("");
        tfYaziciName.setText("");
        tfRefNumber.setText("");
        tfSiraNumber.setText("");
        tfSutunNumber.setText("");
        tfBookId.setText("");
        taBookAbout.setText("");
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel tableModel = (DefaultTableModel) tbBook.getModel();
        for (AddKitabxana ak : db.allBook()) {
            tableModel.addRow(new Object[]{ak.getId(), ak.getBookName(), ak.getYaziciName(), ak.getBookSort(), ak.getRefNumber(), ak.getSiraNumber(), ak.getSutunNumber(), ak.getBookAbout()});
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookKitabxana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookKitabxana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookKitabxana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookKitabxana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookKitabxana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnUpdateBook;
    private javax.swing.JComboBox cmbBookSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBookAbout;
    private javax.swing.JLabel lblMainMenu;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JTextArea taBookAbout;
    private javax.swing.JTable tbBook;
    private javax.swing.JTextField tfBookId;
    private javax.swing.JTextField tfBookName;
    private javax.swing.JTextField tfRefNumber;
    private javax.swing.JTextField tfSiraNumber;
    private javax.swing.JTextField tfSutunNumber;
    private javax.swing.JTextField tfYaziciName;
    // End of variables declaration//GEN-END:variables
}
